# POST http://localhost:3001/api/sense_time/web_hook
POST http://localhost:8088/api/sense_time/web_hook
Content-Type: application/json 

{
	"messageId": "8e7861ac-1376-4b94-8df5-eac8f4eee2f7",
	"eventType": 30000,
	"data": {
		"id": 1957,
		"userId": 223,
		"name": "Jay",
		"type": 2,
		"avatar": "6007ba3293841300017cc4c7",
		"direction": 1,
		"verifyScore": 0.937,
		"receptionUserId": 197,
		"receptionUserName": "staff kk",
		"groups": [[null]],
		"deviceName": "Thunder-E Mini",
		"sn": "SPSE-1db95b332209e9c55351e7d3c9885dff",
		"signDate": "2021-01-29",
		"signTime": 1611901999,
		"signAvatar": "6013ac2f93841300018d26ca",
		"signBgAvatar": "6013ac2f93841300018d26cb",
		"heatAvatar": "6013ac2f93841300018d26cc",
		"companyId": 1,
		"mobile": "99998888",
		"icNumber": "",
		"idNumber": "9yxKkf9MFJNBgLsa8BhkYA==",
		"jobNumber": "",
		"remark": "",
		"entryMode": 1,
		"signTimeZone": "+08:00",
		"docPhoto": "",
		"latitude": 0,
		"longitude": 0,
		"address": "",
		"location": "Entrance",
		"abnormalType": 0,
		"userIcNumber": "",
		"userIdNumber": "9yxKkf9MFJNBgLsa8BhkYA==",
		"bodyTemperature": 34.25,
		"mask": 2
	},
	"sendTime": 1611901999270
}