POST http://localhost:8787/api/pi/getLastActionId HTTP/1.1
Content-Type: application/json

{
	"controllerId": 1
}

#####

POST http://localhost:8787/api/pi/getLastActionId HTTP/1.1
Content-Type: application/json

{
	"controllerId": 2
}