export enum ScanVisitorResult {
  // OK = "OK",
  STAFF_OK = "STAFF_OK",
  STAFF_NOT_FOUND = "STAFF_NOT_FOUND",
  STRANGER_OK = "STRANGER_OK",
  // NOT_FOUND = "NOT_FOUND",
  ERROR = "ERROR",
  // BLACKLIST = "BLACKLIST",
  // QUOTA_FULL = "QUOTA_FULL",
  // ESCORT_REQUIRED = "ESCORT_REQUIRED",
}
