version: v1

port: 3000

senseTimeApiUrl: http://192.168.18.7:8080/vmciif

timeout: 7000

db:
  server: localhost
  port: 1433
  user: sa
  password: W0rdpa55#123
  database: SUNRAY_VMC
  pool:
    min: 5
    max: 5
    idleTimeoutMillis: 1
  options:
    useUTC: false
