version: v1

port: 3000

senseTimeApiUrl: http://localhost:8080/vmciif

timeout: 3000

db:
  server: localhost
  port: 1433
  user: ccheeren
  password: P@#ss2021*
  database: HEEREN_VMC
  pool:
    min: 5
    max: 5
    idleTimeoutMillis: 1
  options:
    useUTC: false

safeEntry:
  prdVenueId: PROD-T21MC0005J-539398-THEHEEREN-SE
  stgVenueId: STG-180000001W-83338-SEQRSELFTESTSINGLE-SE
