version: v1

port: 3000

senseTimeApiUrl: http://localhost:8080/vmciif

timeout: 3000

db:
  server: localhost
  port: 1433
  user: sa
  password: drone
  database: HEEREN_VMC
  pool:
    min: 5
    max: 5
    idleTimeoutMillis: 1
  options:
    useUTC: false

safeEntry:
  prdVenueId: PROD-201926999N-637796-CENTRICORE-SE
  stgVenueId: STG-180000001W-83338-SEQRSELFTESTSINGLE-SE

# ttsh_kiosk
# vmc
# ttsh_gantry
demoMode: vmc

sioUrl: http://127.0.0.1:4001

redis:
  # host: 192.168.18.10
  host: localhost
  port: 6379
